import streamlit as st
import google.generativeai as genai
import os
import json
import sys

# --- Path Setup ---
# This allows us to import from the parent directory (study_agent)
# where 'agents' and 'utils' folders are.
current_dir = os.path.dirname(__file__)
parent_dir = os.path.abspath(os.path.join(current_dir, '..'))
sys.path.append(parent_dir)

try:
    from utils.pdf_utils import extract_text_from_pdf
    from agents.generation_agent import get_study_aids
    from agents.planner import create_revision_plan
except ImportError as e:
    st.error(f"Error importing modules: {e}. Make sure all files are in the correct structure.")
    st.stop()

# --- Page Configuration ---
st.set_page_config(
    page_title="Autonomous Study Agent",
    page_icon="🤖",
    layout="wide"
)

# --- API Key Configuration ---
# We need to configure the Gemini API key.
# First, try to get it from Streamlit secrets (for deployment)
# If not, try environment variables (for local development)
api_key = None
api_key_configured = False

try:
    if "GOOGLE_API_KEY" in st.secrets:
        api_key = st.secrets["GOOGLE_API_KEY"]
    else:
        api_key = os.environ.get("GOOGLE_API_KEY")

    if api_key:
        genai.configure(api_key=api_key)
        api_key_configured = True
    
except Exception:
    # This can happen if st.secrets is not available (e.g., local run without secrets.toml)
    api_key = os.environ.get("GOOGLE_API_KEY")
    if api_key:
        genai.configure(api_key=api_key)
        api_key_configured = True

if not api_key_configured:
    st.error("Google API Key not configured.")
    st.write("Please set your `GOOGLE_API_KEY` in Streamlit secrets (`.streamlit/secrets.toml`) or as an environment variable.")
    # Fallback to text input for local testing
    api_key_input = st.text_input("Or enter your Google API Key here to proceed:", type="password")
    if api_key_input:
        genai.configure(api_key=api_key_input)
        api_key_configured = True
    else:
        st.stop() # Stop execution if no key is provided

# --- Session State Initialization ---
# This helps store results so they don't disappear
if 'study_aids' not in st.session_state:
    st.session_state.study_aids = None
if 'error' not in st.session_state:
    st.session_state.error = None

# --- UI ---
st.title("🤖 Autonomous Study Agent")
st.write("Upload your PDF notes (uwu) and get AI-generated flashcards, quizzes, and a revision plan!")

uploaded_file = st.file_uploader("Upload Your Notes (PDF)", type="pdf")

if uploaded_file:
    if st.button("Generate Study Aids"):
        # Clear previous results
        st.session_state.study_aids = None
        st.session_state.error = None
        
        try:
            with st.spinner("Reading PDF..."):
                pdf_bytes = uploaded_file.read() # Read bytes from uploaded file
                pdf_text = extract_text_from_pdf(pdf_bytes)
            
            with st.spinner("Asking Gemini to create study aids... (this may take a moment)"):
                study_aids_json = get_study_aids(pdf_text)
                
            with st.spinner("Creating revision plan..."):
                # Use the 'topics' list generated by Gemini
                revision_plan = create_revision_plan(study_aids_json.get("topics", []))
            
            # Store everything in session state
            st.session_state.study_aids = {
                "flashcards": study_aids_json.get("flashcards", []),
                "quiz": study_aids_json.get("quiz", []),
                "plan": revision_plan,
            }
            st.success("Successfully generated study aids!")

        except Exception as e:
            st.error(f"An error occurred: {e}")
            st.session_state.error = str(e)

# --- Display Results ---
if st.session_state.study_aids:
    aids = st.session_state.study_aids
    
    # Create directories if they don't exist
    os.makedirs("outputs", exist_ok=True)
    
    tab1, tab2, tab3 = st.tabs(["Flashcards", "Quiz", "Revision Plan"])
    
    with tab1:
        st.header("Flashcards")
        st.write("Click on a card to see the answer.")
        
        if not aids["flashcards"]:
            st.warning("No flashcards were generated.")
        
        for i, card in enumerate(aids["flashcards"]):
            # Use st.expander for a simple "flip" effect
            with st.expander(f"**Q: {card['question']}**"):
                st.write(f"**A:** {card['answer']}")
        
        # Save to JSON as per PDF
        try:
            with open("outputs/flashcards.json", "w", encoding="utf-8") as f:
                json.dump(aids["flashcards"], f, indent=2)
            st.toast("Flashcards saved to outputs/flashcards.json")
        except Exception as e:
            st.warning(f"Could not save flashcards.json: {e}")

    with tab2:
        st.header("Quiz")
        if not aids["quiz"]:
            st.warning("No quiz questions were generated.")
        
        for i, q in enumerate(aids["quiz"]):
            st.subheader(f"Question {i+1}: {q['question']}")
            
            options = q.get('options', [])
            answer = st.radio(
                "Choose one:", 
                options, 
                key=f"quiz_{i}",
                index=None # Default to no selection
            )
            
            # Use session state to store check status
            if f"check_{i}" not in st.session_state:
                st.session_state[f"check_{i}"] = False

            if st.button(f"Check Answer {i+1}", key=f"btn_{i}"):
                st.session_state[f"check_{i}"] = True # Mark as checked

            if st.session_state[f"check_{i}"]:
                if answer == q['answer']:
                    st.success(f"Correct! The answer is: {q['answer']}")
                elif answer is not None:
                    st.error(f"Not quite. The correct answer is: {q['answer']}")
                else:
                    st.info("Please select an answer to check.")

        # Save to JSON
        try:
            with open("outputs/quizzes.json", "w", encoding="utf-8") as f:
                json.dump(aids["quiz"], f, indent=2)
            st.toast("Quiz saved to outputs/quizzes.json")
        except Exception as e:
            st.warning(f"Could not save quizzes.json: {e}")

    with tab3:
        st.header("Revision Plan")
        if not aids["plan"]:
            st.warning("No revision plan was generated.")
        
        st.write("Here is a suggested revision schedule for the main topics:")
        for item in aids["plan"]:
            st.write(f"🗓️ **{item['topic']}**: Revise on `{item['revise_on']}`")
        
        # Save to JSON
        try:
            with open("outputs/planner.json", "w", encoding="utf-8") as f:
                json.dump(aids["plan"], f, indent=2)
            st.toast("Plan saved to outputs/planner.json")
        except Exception as e:
            st.warning(f"Could not save planner.json: {e}")

elif st.session_state.error:
    st.error(f"Failed to generate aids. Please try again. Error: {st.session_state.error}")